"""
Django settings for api_channel project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
envs = os.environ

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = envs.get('DJANGO_SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# 
MODELS_PATH= envs.get('MODELS_PATH', 'trained_models')
PINECONE_API_KEY= envs.get('PINECONE_API_KEY', '')
PINECONE_INDEX_NAME= envs.get('PINECONE_INDEX_NAME', '')



HOST=envs.get("HOST_SERVER_URL",'http://localhost:8000')
API_KEY = envs.get('API_KEY', '')

ALLOWED_HOSTS = ["*"]
# 
# MySQL eliminado - Sistema de usuarios deshabilitado
CUSTOM_APPS=['data_extraction', 'stamp_detection']

MIGRATION_MODULES = {
    **{'auth': None,
    'admin':None,
    'contenttypes': None,
    'sessions': None,},**{x:None for x in CUSTOM_APPS}
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders', 
    'drf_yasg',
]+CUSTOM_APPS

MIDDLEWARE = [
    'custom_lib.custom_middleware.MaintenanceModeMiddleware',  # Primer middleware para interceptar en modo mantenimiento
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'custom_lib.custom_middleware.ErrorHandlerMiddleware',
]

ROOT_URLCONF = 'api_channel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_channel.wsgi.application'

# SQLite configuration - No external database needed
# This reduces costs significantly as no MySQL server is required
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR/'productionfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [origin for origin in envs.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin]


LOG_DELETION=envs.get('LOG_DELETION_DAY', 15)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': ['custom_lib.renderer.JSONResponseRenderer'],

}
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'X-Api-Key',
            'description': 'API Key authentication'
        }
    },
    'JSON_EDITOR': True,
    'TAGS_SORTER':'alpha',
    'MAX_DISPLAYED_TAGS':1
}

# 
import json
ERROR_FILE_PATH=os.path.join(BASE_DIR,"error_code.json")
ERROR_JSON={}
try:
    ERROR_JSON = json.loads(open(ERROR_FILE_PATH).read())
except Exception as e:
    print(e)


CORS_ORIGIN_ALLOW_ALL = True
