#!/bin/bash
# Script para configurar variables en Railway manualmente

echo "=========================================="
echo "  INSTRUCCIONES PARA RAILWAY"
echo "=========================================="
echo ""
echo "1. Ve a: https://railway.com/project/cf2e44c8-71ee-4b40-bfd0-513dbe50ea16"
echo ""
echo "2. Haz clic en tu servicio (aparecerá después del deploy)"
echo ""
echo "3. Ve a la pestaña 'Variables'"
echo ""
echo "4. Agrega estas variables (una por una):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "DJANGO_SECRET_KEY"
echo "django-insecure-f@c6_4-oqw7#g!62&pqgdo0w657xt@epq*a^$8nt48oaop6nr6"
echo ""
echo "JWT_AUTH_SECRET"
echo "fdxqjcqi63843bixvqlibhcwc632"
echo ""
echo "AUTH_TOKEN_EXPIRE_TIME"
echo "1440"
echo ""
echo "PINECONE_API_KEY"
echo "5f08a0a8-f685-41e4-9d66-f0464852bb26"
echo ""
echo "PINECONE_INDEX_NAME"
echo "iaimages"
echo ""
echo "MODELS_PATH"
echo "trained_models"
echo ""
echo "TOKENIZERS_PARALLELISM"
echo "false"
echo ""
echo "JUPYTER_PLATFORM_DIRS"
echo "1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5. IMPORTANTE: Para la base de datos MySQL:"
echo "   a. En Railway, haz clic en 'New' -> 'Database' -> 'Add MySQL'"
echo "   b. Esto creará automáticamente estas variables:"
echo "      - MYSQL_HOST"
echo "      - MYSQL_PORT" 
echo "      - MYSQL_USER"
echo "      - MYSQL_PASSWORD"
echo "      - MYSQL_DATABASE"
echo ""
echo "   c. Luego agrega estas variables apuntando a las de MySQL:"
echo "      DJANGO_DATABASE_SERVER=\${{MYSQL_HOST}}"
echo "      DJANGO_DATABASE_NAME=\${{MYSQL_DATABASE}}"
echo "      DJANGO_DATABASE_USER=\${{MYSQL_USER}}"
echo "      DJANGO_DATABASE_PASSWORD=\${{MYSQL_PASSWORD}}"
echo ""
echo "6. Guarda los cambios y Railway redesplegará automáticamente"
echo ""
echo "=========================================="
